In [3]:
import numpy as np 
import pandas as pd 

In [50]:
x1 = np.random.normal(0, 1, 1000)
x2 = np.random.normal(0, 1, 1000)
x3 = np.random.normal(0, 1, 1000)


np.cov([x1, x2, x3])

array([[ 0.94235194,  0.02057838,  0.03011899],
       [ 0.02057838,  0.97390655, -0.0137131 ],
       [ 0.03011899, -0.0137131 ,  1.0204094 ]])

In [46]:
np.arange(10, dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.cov(np.random.rand(1000, 3))

array([[ 0.07837962,  0.00383169,  0.0296802 , ...,  0.01033446,
        -0.02582093, -0.03469185],
       [ 0.00383169,  0.0041708 ,  0.00357638, ..., -0.0030486 ,
        -0.0001529 ,  0.00814101],
       [ 0.0296802 ,  0.00357638,  0.01237312, ...,  0.0020172 ,
        -0.00918574, -0.00788823],
       ...,
       [ 0.01033446, -0.0030486 ,  0.0020172 , ...,  0.0045331 ,
        -0.00439426, -0.0133501 ],
       [-0.02582093, -0.0001529 , -0.00918574, ..., -0.00439426,
         0.00881526,  0.01416826],
       [-0.03469185,  0.00814101, -0.00788823, ..., -0.0133501 ,
         0.01416826,  0.03964686]])

In [2]:
df = pd.read_csv('https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv')

/tmp/ipykernel_59359/3738925007.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv')


In [5]:
us = df.loc[df.country_region == 'United States']

In [7]:
us.date = pd.to_datetime(us.date)

# narrow to April 10 2020 and April 24 2020

us = us.loc[(us.date >= '2020-04-10') & (us.date <= '2020-04-24')]

/tmp/ipykernel_59359/185694691.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us.date = pd.to_datetime(us.date)


In [11]:
us.to_parquet('us_mobility.parquet')

In [4]:
us = pd.read_parquet('us_mobility.parquet')

In [5]:
us.to_csv('us_mobility.csv')